// Code generated by MockGen. DO NOT EDIT.
// Source: adapter.go

// Package chatadapter is a generated GoMock package.
package chatadapter

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// ReceiveMessage mocks base method.
func (m *MockAdapter) ReceiveMessage(req ReceiveMessageReq) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveMessage", req)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveMessage indicates an expected call of ReceiveMessage.
func (mr *MockAdapterMockRecorder) ReceiveMessage(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveMessage", reflect.TypeOf((*MockAdapter)(nil).ReceiveMessage), req)
}

// WebsocketHandler mocks base method.
func (m *MockAdapter) WebsocketHandler(req WebsocketHandlerReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebsocketHandler", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// WebsocketHandler indicates an expected call of WebsocketHandler.
func (mr *MockAdapterMockRecorder) WebsocketHandler(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebsocketHandler", reflect.TypeOf((*MockAdapter)(nil).WebsocketHandler), req)
}
