// Code generated by MockGen. DO NOT EDIT.
// Source: adapter.go

// Package loggeradapter is a generated GoMock package.
package loggeradapter

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// NewError mocks base method.
func (m *MockAdapter) NewError(logString string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NewError", logString)
}

// NewError indicates an expected call of NewError.
func (mr *MockAdapterMockRecorder) NewError(logString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewError", reflect.TypeOf((*MockAdapter)(nil).NewError), logString)
}

// NewInfo mocks base method.
func (m *MockAdapter) NewInfo(logString string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NewInfo", logString)
}

// NewInfo indicates an expected call of NewInfo.
func (mr *MockAdapterMockRecorder) NewInfo(logString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewInfo", reflect.TypeOf((*MockAdapter)(nil).NewInfo), logString)
}
