// Code generated by MockGen. DO NOT EDIT.
// Source: repoadapter.go

// Package databaseadapter is a generated GoMock package.
package databaseadapter

import (
	reflect "reflect"
	models "websocket_client/internal/pkg/platform/mysql/models"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockRepoAdapter is a mock of RepoAdapter interface.
type MockRepoAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockRepoAdapterMockRecorder
}

// MockRepoAdapterMockRecorder is the mock recorder for MockRepoAdapter.
type MockRepoAdapterMockRecorder struct {
	mock *MockRepoAdapter
}

// NewMockRepoAdapter creates a new mock instance.
func NewMockRepoAdapter(ctrl *gomock.Controller) *MockRepoAdapter {
	mock := &MockRepoAdapter{ctrl: ctrl}
	mock.recorder = &MockRepoAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoAdapter) EXPECT() *MockRepoAdapterMockRecorder {
	return m.recorder
}

// AddFriend mocks base method.
func (m *MockRepoAdapter) AddFriend(req AddFriendReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFriend", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFriend indicates an expected call of AddFriend.
func (mr *MockRepoAdapterMockRecorder) AddFriend(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFriend", reflect.TypeOf((*MockRepoAdapter)(nil).AddFriend), req)
}

// DoCustomTransaction mocks base method.
func (m *MockRepoAdapter) DoCustomTransaction(fc func(*gorm.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoCustomTransaction", fc)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoCustomTransaction indicates an expected call of DoCustomTransaction.
func (mr *MockRepoAdapterMockRecorder) DoCustomTransaction(fc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoCustomTransaction", reflect.TypeOf((*MockRepoAdapter)(nil).DoCustomTransaction), fc)
}

// GetAccount mocks base method.
func (m *MockRepoAdapter) GetAccount(req GetAccountReq) (models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", req)
	ret0, _ := ret[0].(models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockRepoAdapterMockRecorder) GetAccount(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockRepoAdapter)(nil).GetAccount), req)
}

// GetChatHistory mocks base method.
func (m *MockRepoAdapter) GetChatHistory(req GetChatHistoryReq) ([]models.Messages, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatHistory", req)
	ret0, _ := ret[0].([]models.Messages)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatHistory indicates an expected call of GetChatHistory.
func (mr *MockRepoAdapterMockRecorder) GetChatHistory(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatHistory", reflect.TypeOf((*MockRepoAdapter)(nil).GetChatHistory), req)
}

// GetUserFriends mocks base method.
func (m *MockRepoAdapter) GetUserFriends(req GetUserFriendsReq) ([]models.UserFriends, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFriends", req)
	ret0, _ := ret[0].([]models.UserFriends)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFriends indicates an expected call of GetUserFriends.
func (mr *MockRepoAdapterMockRecorder) GetUserFriends(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFriends", reflect.TypeOf((*MockRepoAdapter)(nil).GetUserFriends), req)
}

// RemoveFriend mocks base method.
func (m *MockRepoAdapter) RemoveFriend(req RemoveFriendReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFriend", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFriend indicates an expected call of RemoveFriend.
func (mr *MockRepoAdapterMockRecorder) RemoveFriend(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFriend", reflect.TypeOf((*MockRepoAdapter)(nil).RemoveFriend), req)
}

// SetAccount mocks base method.
func (m *MockRepoAdapter) SetAccount(req SetAccountReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAccount", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAccount indicates an expected call of SetAccount.
func (mr *MockRepoAdapterMockRecorder) SetAccount(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAccount", reflect.TypeOf((*MockRepoAdapter)(nil).SetAccount), req)
}
