// Code generated by MockGen. DO NOT EDIT.
// Source: adapter.go

// Package wsprocessoradapter is a generated GoMock package.
package wsprocessoradapter

import (
	reflect "reflect"
	wsconnadapter "websocket_client/internal/pkg/core/adapter/wsconnadapter"

	gomock "github.com/golang/mock/gomock"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// ProcessWebsocketAfterUpgrade mocks base method.
func (m *MockAdapter) ProcessWebsocketAfterUpgrade(conn wsconnadapter.Adapter, userID string, callChatServiceFunc func([]byte, string, string) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessWebsocketAfterUpgrade", conn, userID, callChatServiceFunc)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessWebsocketAfterUpgrade indicates an expected call of ProcessWebsocketAfterUpgrade.
func (mr *MockAdapterMockRecorder) ProcessWebsocketAfterUpgrade(conn, userID, callChatServiceFunc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessWebsocketAfterUpgrade", reflect.TypeOf((*MockAdapter)(nil).ProcessWebsocketAfterUpgrade), conn, userID, callChatServiceFunc)
}
