// Code generated by MockGen. DO NOT EDIT.
// Source: repoadapter.go

// Package kvadapter is a generated GoMock package.
package kvadapter

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepoAdapter is a mock of RepoAdapter interface.
type MockRepoAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockRepoAdapterMockRecorder
}

// MockRepoAdapterMockRecorder is the mock recorder for MockRepoAdapter.
type MockRepoAdapterMockRecorder struct {
	mock *MockRepoAdapter
}

// NewMockRepoAdapter creates a new mock instance.
func NewMockRepoAdapter(ctrl *gomock.Controller) *MockRepoAdapter {
	mock := &MockRepoAdapter{ctrl: ctrl}
	mock.recorder = &MockRepoAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoAdapter) EXPECT() *MockRepoAdapterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRepoAdapter) Delete(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepoAdapterMockRecorder) Delete(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepoAdapter)(nil).Delete), key)
}

// GetValue mocks base method.
func (m *MockRepoAdapter) GetValue(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValue indicates an expected call of GetValue.
func (mr *MockRepoAdapterMockRecorder) GetValue(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockRepoAdapter)(nil).GetValue), key)
}

// SetValueUntilChannelClose mocks base method.
func (m *MockRepoAdapter) SetValueUntilChannelClose(key, data string, ttl int, isOpen *bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetValueUntilChannelClose", key, data, ttl, isOpen)
}

// SetValueUntilChannelClose indicates an expected call of SetValueUntilChannelClose.
func (mr *MockRepoAdapterMockRecorder) SetValueUntilChannelClose(key, data, ttl, isOpen interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetValueUntilChannelClose", reflect.TypeOf((*MockRepoAdapter)(nil).SetValueUntilChannelClose), key, data, ttl, isOpen)
}
