// Code generated by MockGen. DO NOT EDIT.
// Source: adapter.go

// Package wsstoreadapter is a generated GoMock package.
package wsstoreadapter

import (
	reflect "reflect"
	wsconnadapter "websocket_client/internal/pkg/core/adapter/wsconnadapter"

	gomock "github.com/golang/mock/gomock"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// AddConn mocks base method.
func (m *MockAdapter) AddConn(conn wsconnadapter.Adapter, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddConn", conn, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddConn indicates an expected call of AddConn.
func (mr *MockAdapterMockRecorder) AddConn(conn, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConn", reflect.TypeOf((*MockAdapter)(nil).AddConn), conn, userID)
}

// DeleteConn mocks base method.
func (m *MockAdapter) DeleteConn(userID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteConn", userID)
}

// DeleteConn indicates an expected call of DeleteConn.
func (mr *MockAdapterMockRecorder) DeleteConn(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConn", reflect.TypeOf((*MockAdapter)(nil).DeleteConn), userID)
}

// GetConn mocks base method.
func (m *MockAdapter) GetConn(userID string) wsconnadapter.Adapter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConn", userID)
	ret0, _ := ret[0].(wsconnadapter.Adapter)
	return ret0
}

// GetConn indicates an expected call of GetConn.
func (mr *MockAdapterMockRecorder) GetConn(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConn", reflect.TypeOf((*MockAdapter)(nil).GetConn), userID)
}

// Release mocks base method.
func (m *MockAdapter) Release(userID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release", userID)
}

// Release indicates an expected call of Release.
func (mr *MockAdapterMockRecorder) Release(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockAdapter)(nil).Release), userID)
}
