// Code generated by MockGen. DO NOT EDIT.
// Source: adapter.go

// Package accountadapter is a generated GoMock package.
package accountadapter

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockAdapter) Register(arg0 RegisterReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockAdapterMockRecorder) Register(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAdapter)(nil).Register), arg0)
}

// VerifyAuth mocks base method.
func (m *MockAdapter) VerifyAuth(arg0 VerifyAuthReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAuth", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyAuth indicates an expected call of VerifyAuth.
func (mr *MockAdapterMockRecorder) VerifyAuth(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAuth", reflect.TypeOf((*MockAdapter)(nil).VerifyAuth), arg0)
}
